apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  annotations:
    # Workload Identity で紐付ける GSA を指定する
    iam.gke.io/gcp-service-account: {{ .Values.serviceAccount.gsaName }}@{{ .Values.django.configMap.googleCloudProject }}.iam.gserviceaccount.com